GET http://localhost:3000/

###get expenses
GET http://localhost:3000/expenses

###get income
GET http://localhost:3000/income

###post income
POST http://localhost:3000/income/add
Content-Type: application/json

{
  "source_name": "sales Work",
  "amount": 800.00,
  "date_received": "2023-10-15"
}

###post expenses
POST http://localhost:3000/expenses/add
Content-Type: application/json

{
    "category": "food",
    "amount": 700.00,
    "date_paid": "2023-10-11"
}

###delete expenses
DELETE http://localhost:3000/expenses/delete/5

###Post users
POST http://localhost:3000/users
Content-Type: application/json

{
    "email": "hei@gmail.com",
    "password": "123456789",
    "fullname": "hei",
    "lastname": "hei",
    "address": "Helsinki",
    "job": "Manager",
    "phone": "4512589654",
    "role":""

}

###get users
GET http://localhost:3000/users

###loginUser
POST http://localhost:3000/login
Content-Type: application/json

{
  "email": "hei@gmail.com",
  "password": "123456789"
}

###get login user by id
GET http://localhost:3000/users/34
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzQsInJvbGUiOiIiLCJpYXQiOjE3Mzg4NjU2NjAsImV4cCI6MTczODg2NTcyMH0.Y1Rp0-6SMydj2JLoXb0eJbBMoWU5ZtRz0MgCHG6-eVU

###
POST http://localhost:3000/refresh-token
Content-Type: application/json
Cookie: refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzQsInJvbGUiOiIiLCJpYXQiOjE3Mzg4NjU1NzksImV4cCI6MTczODg4MzU3OX0.YjI9Bof_0iMFkNYcc1Rrs6JVIP9p6av3MgxV-12F-TM