GET http://localhost:3000/

###get expenses
GET http://localhost:3000/expenses

###get income
GET http://localhost:3000/income

###post income
POST http://localhost:3000/income/add
Content-Type: application/json

{
  "source_name": "sales Work",
  "amount": 800.00,
  "date_received": "2023-10-15"
}

###post expenses
POST http://localhost:3000/expenses/add
Content-Type: application/json

{
    "category": "food",
    "amount": 700.00,
    "date_paid": "2023-10-11"
}